### ISSUE TITLE
LM Studio 0.3.5 being flagged as malware on windows 11

### ISSUE THREAD

**Issue by shaafekhan** [lmstudio-ai/lmstudio-bug-tracker#166]
Hi. Windows 11 is catching LM Studio 0.3.5 as malware. It says that it contains the "Trojan:Win32/Cinjo.O!cl" malware. Not sure if this is a false positive.

Screenshots
<img width="535" alt="av" src="https://github.com/user-attachments/assets/f63e7f27-ef47-4f50-b6e6-e723dd08da24">

Steps to reproduce
What were you doing right before this issue happened?
I just clicked on the shortcut of LM Studio EXE file on my desktop.
If applicable, mention exactly which model you were using
No model was used, was just booting LM Studio

My setup
Operating system
Windows 11 Business Version	10.0.22621 Build 22621

RAM
32 GB
GPU type GPU VRAM (for non-Mac)
Intel
Processor type
Processor	13th Gen Intel(R) Core(TM) i5-1335U, 1300 Mhz, 10 Core(s), 12 Logical Processor(s)

**Comment by yagil** [comment]
Thanks. This is a false positive, as far as it’s possible to know for sure

**Comment by HenkPoley** [comment]
I'm seeing the same Trojan:Win32/Cinjo.O!cl detection on LM Studio 0.3.7 Build 2.

Could it be this issue? https://github.com/electron-userland/electron-builder/issues/5759

>  It seems that my publiserName is not completely match the name set in the certificate, which cause windows defender detect it as malware.
>
> for others who come up this problem, **please make sure config.win.publisherName in your build params is completely match the name you set in your code certificate**.

~~Edit: I'm not seeing obvious difference between the certificate and names under the details tab in Windows Explorer though.~~

~~Maybe that there is 3x "LM Studio" in the certificate, but there is only 2 under details, for example there is no 'Internal Name' under details.~~

**Comment by HenkPoley** [comment]
Wait.. (still no malware) but for the LM Studio.exe:

"Signature verification
File is not signed"

E.g. there are lots of signatures (chains) in the file. 

But **none of them sign the exe** itself.

https://www.virustotal.com/gui/file/4b6ef1baca34039c8e1f0e7203eb0fd44490d636b02ea58a10cde6797871448c/details

**Comment by Hackitfree** [comment]
So many times (like always) when I run LMStudio - the AV (Webroot) starts working overtime slowing down things ...
Even when I added the exe - the whole DIR and models DIR to AV exclusions - everything LMStudio related - it still freaks out when trying to start it or switch or load different model .
Its same since day-one - I hoped this last update will fix it but - no ... 😨

**Comment by HenkPoley** [comment]
0.3.9 build 5 is also reported as "Trojan:Win32/Cinjo.O!cl" by Windows Defender.

**Comment by franklesniak** [comment]
I just had this happen on v0.3.12 after auto-updating from v0.3.10.

**Comment by n12k0** [comment]
I receive a positive result whenever I attempt to upload a document. The upload is blocked, and Kaspersky identifies the file as: 

Type: Trojan, Name: PDM:Exploit.Win32.Generic. 

Tried with several documents.

**Comment by n12k0** [comment]
Forgot to add that I am on the 0.3.12 (Build 1) version.

**Comment by HenkPoley** [comment]
I think LM Studio needs to properly sign the executable. Currently it looks just like a generic chromium "dropper" that immediately starts downloading a command file with new potential downloads.

Without signing, it won't build up reputation. But stay with the (potential) malware pool.

**Comment by yagil** [comment]
> I think LM Studio needs to properly sign the executable. Currently it looks just like a generic chromium "dropper" that immediately starts downloading a command file with new potential downloads.
> 
> Without signing, it won't build up reputation. But stay with the (potential) malware pool.

What? This is not what LM Studio does + of course we sign the software. What are you basing this on?

**Comment by n12k0** [comment]
@yagil, do you have any idea what's causing this? While I am sure its a false positive, i would like to know the root cause.

**Comment by yagil** [comment]
> [@yagil](https://github.com/yagil), do you have any idea what's causing this? While I am sure its a false positive, i would like to know the root cause.

I would love to know as well. As a starting point, would you be able to share screenshots / other output from your antivirus? 

Also can you confirm you downloaded the app from https://lmstudio.ai only?

Btw this issue might be better: https://github.com/lmstudio-ai/lmstudio-bug-tracker/issues/500

**Comment by HenkPoley** [comment]
> > I think LM Studio needs to properly sign the executable. Currently it looks just like a generic chromium "dropper" that immediately starts downloading a command file with new potential downloads.
> > Without signing, it won't build up reputation. But stay with the (potential) malware pool.
> 
> What? This is not what LM Studio does + of course we sign the software. What are you basing this on?

I base this on:

https://www.virustotal.com/gui/file/4b6ef1baca34039c8e1f0e7203eb0fd44490d636b02ea58a10cde6797871448c/details

Signature verification
File is not signed

Edit: 0.3.13 shows the same issue: https://www.virustotal.com/gui/file/85711fea6f99b8419f9f36b67a986978f2b0213b4e12dfacfe097249bb0b8fe1/details

Possibly VirusTotal is wrong. But at least some software doesn't agree the LM Studio.exe is signed. So that might as well happen in some corners of Windows. Just pointing that out.

You might also discuss with some Microsoft Defender people how to make the software look less like a 'dropper'. Maybe put the downloading of updates behind a popup + button, so it's not autonomously replacing exes.

**Comment by HenkPoley** [comment]
This is the 'Digital signatures' tab of LM Studio.exe 0.3.13 (Build 2) in Windows Explorer:

![Image](https://github.com/user-attachments/assets/84d3aca2-16b1-42b6-bd29-ea2772daaa63)

Yes, it's Dutch. But you can clearly see there are _no signatures listed_.

**Comment by HenkPoley** [comment]
Not signed issue still exists for LM Studio 0.3.13 build 2: https://www.virustotal.com/gui/file/85711fea6f99b8419f9f36b67a986978f2b0213b4e12dfacfe097249bb0b8fe1/detection

**Comment by HenkPoley** [comment]
There is now a beta version that is signed, this _ought_ to fix this issue. Fingers crossed.

https://github.com/lmstudio-ai/lmstudio-bug-tracker/issues/500#issuecomment-2749832923

**Comment by computerline-cmyk** [comment]
Malware can read all your data and send it to attacker

**Comment by killerkuwalski** [comment]
Wanted to follow up on this as not sure if there's another thread but this was the first one I found. Just downloaded the most recent version of the installer from the website and it flagged the installer as malware, not sure anything else as windows defender just failed the download.

**Comment by killerkuwalski** [comment]
Sorry for second comment with documentation, figured out how to get to windows security lol

<img width="913" height="771" alt="Image" src="https://github.com/user-attachments/assets/dc7e9ec5-4c83-4fc9-b45b-33db4086ffb1" />

**Comment by HenkPoley** [comment]
Hmm, 12 hours ago it was clean on VirusTotal: https://www.virustotal.com/gui/file/4c4e6c9738bca9904e5e21cb16258672bd7eba7680cb185d68aa5bcbb05f1b94

Kicked off a new scan, and it still says clean. Do note that these tend to be file pattern based scans, and not behaviour based detectors. But, none of the behaviour sandboxes on VirusTotal trigger either.

It also reports:

> Signature Verification
> Signed file, valid signature

So that's OK as well. 👍

Btw, `Trojan:Script/Wacatac.H!ml` is some generic heuristic detection. `ml` is for "machine learning". And I believe Wacatac is some detection for programmatically requesting elevated User Account Control (UAC) permissions (but I might be wrong about that).

A False Positive. Microsoft Edge tends to have a "report as safe" option somewhere in the download menu.
