### ISSUE TITLE
GPU not utilising as intended 

### ISSUE THREAD

**Issue by Xplo8E** [lmstudio-ai/lmstudio-bug-tracker#64]
I'm experiencing an issue with my NVIDIA RTX 3050 (4GB VRAM) and 16GB RAM setup in LM Studio. Specifically, I've been running the LLaMA 3 8B model with GPU layers set to 20 and CPU threads set to 8, which is the configuration I've settled on after experimenting with different settings.

![IMG-20240725-WA0010.jpg](https://github.com/user-attachments/assets/64547415-4de9-41fe-893f-e34784381ac6)

However, today I noticed that LM Studio is not utilizing my GPU as it normally does - previously, it would use around 50% of the GPU's capacity, but now it seems to be underutilizing it and cpu usage increased. 

Could you please let me know if there's something I'm doing wrong or if I've missed a crucial setting? I'd appreciate your input on this matter.

**Comment by MNLierman** [comment]
For anyone else that is wondering, I seem to have solved my problem by adjusting the global parameters. If you want the model to consume all available GPU power you decrease the CPU threads to 1 and increase the GPU layers to as high as it goes. Slide it all the way to the right. You can also do something like use 2 CPU threads and max the GPU layers, which would leave a little buffer of GPU power in case you're doing other things like watching a movie. Play with these options. Some say that models start to behave strangely if the context is too high. The model I was using earlier has a context max of 131k and I was only using 6k so that didn't fit. This is when I started drastically changing the options until I found what worked.
